domain_path: /home/kimyujeong/workspace_ondevice_2/09.wafer_npu_project/vitis_ws_new/wafer_npu_platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /opt/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
