#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Jul 01 14:33:15 KST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/opt/Xilinx/Vivado/2024.2/data"

# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_19 -L processing_system7_vip_v1_0_21 -L xilinx_vip -prj tb_conv_layer_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_19 -L processing_system7_vip_v1_0_21 -L xilinx_vip -prj tb_conv_layer_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
