# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Zybo-Z7-Master.xdc

# Block Designs: bd/wafer_npu_bd/wafer_npu_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd || ORIG_REF_NAME==wafer_npu_bd} -quiet] -quiet

# IP: bd/wafer_npu_bd/ip/wafer_npu_bd_processing_system7_0_0/wafer_npu_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd_processing_system7_0_0 || ORIG_REF_NAME==wafer_npu_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/wafer_npu_bd/ip/wafer_npu_bd_cnn_npu_0_0/wafer_npu_bd_cnn_npu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd_cnn_npu_0_0 || ORIG_REF_NAME==wafer_npu_bd_cnn_npu_0_0} -quiet] -quiet

# IP: bd/wafer_npu_bd/ip/wafer_npu_bd_ps7_0_axi_periph_imp_auto_pc_0/wafer_npu_bd_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==wafer_npu_bd_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/wafer_npu_bd/ip/wafer_npu_bd_ps7_0_axi_periph_0/wafer_npu_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==wafer_npu_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/wafer_npu_bd/ip/wafer_npu_bd_rst_ps7_0_40M_0/wafer_npu_bd_rst_ps7_0_40M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wafer_npu_bd_rst_ps7_0_40M_0 || ORIG_REF_NAME==wafer_npu_bd_rst_ps7_0_40M_0} -quiet] -quiet

# XDC: /home/kimyujeong/workspace_ondevice_2/09.wafer_npu_project/C_vivado/C_vivado.gen/sources_1/bd/wafer_npu_bd/wafer_npu_bd_ooc.xdc
